"""log feed key and allow orphan entries in feed_publish_log

Revision ID: 131d683e6b15
Revises: 6f840bfbc3e9
Create Date: 2026-09-19 16:26:02.537851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '131d683e6b15'
down_revision: Union[str, None] = '6f840bfbc3e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed_publish_log', sa.Column('feed_source', sa.String(length=64), nullable=True))
    op.add_column('feed_publish_log', sa.Column('feed_source_job_id', sa.String(length=255), nullable=True))
    op.alter_column('feed_publish_log', 'job_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feed_publish_log', 'job_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('feed_publish_log', 'feed_source_job_id')
    op.drop_column('feed_publish_log', 'feed_source')
    # ### end Alembic commands ###
