"""add feed publication tables

Revision ID: 47cf46f2c809
Revises: 18a1520ba1e1
Create Date: 2026-09-19 06:48:35.438632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47cf46f2c809'
down_revision: Union[str, None] = '18a1520ba1e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed_publications',
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('feed_source', sa.String(length=64), nullable=False),
    sa.Column('feed_source_job_id', sa.String(length=255), nullable=False),
    sa.Column('sent_hash', sa.String(length=64), nullable=False),
    sa.Column('last_result', sa.String(length=16), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('feed_status', sa.String(length=16), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('job_id'),
    sa.UniqueConstraint('feed_source', 'feed_source_job_id', name='uq_feed_publications_feed_key')
    )
    op.create_table('feed_publish_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('constraint_name', sa.String(length=128), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_publish_log_job_id'), 'feed_publish_log', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feed_publish_log_job_id'), table_name='feed_publish_log')
    op.drop_table('feed_publish_log')
    op.drop_table('feed_publications')
    # ### end Alembic commands ###
