"""track ats board and consecutive misses on jobs

Revision ID: 6f840bfbc3e9
Revises: 47cf46f2c809
Create Date: 2026-09-19 16:23:47.363733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f840bfbc3e9'
down_revision: Union[str, None] = '47cf46f2c809'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('ats_board_token', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column('consecutive_misses', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'consecutive_misses')
    op.drop_column('jobs', 'ats_board_token')
    # ### end Alembic commands ###
