"""initial schema

Revision ID: 71ecdb7d359c
Revises: 
Create Date: 2026-09-18 07:01:22.650189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '71ecdb7d359c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ats_companies',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('ats_platform', sa.String(length=32), nullable=False),
    sa.Column('board_token', sa.String(length=255), nullable=False),
    sa.Column('source_of_discovery', sa.String(length=32), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ats_platform', 'board_token', name='uq_ats_companies_platform_token')
    )
    op.create_index('ix_ats_companies_enabled_platform', 'ats_companies', ['enabled', 'ats_platform'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('job_title', sa.String(length=512), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_job_id', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('direct_apply_url', sa.Text(), nullable=True),
    sa.Column('level', sa.String(length=16), nullable=True),
    sa.Column('role_category', sa.String(length=64), nullable=True),
    sa.Column('main_stack', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('full_technology_stack', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('required_years_experience', sa.Integer(), nullable=True),
    sa.Column('employment_type', sa.String(length=32), nullable=True),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('is_remote', sa.Boolean(), nullable=True),
    sa.Column('us_eligible', sa.Boolean(), nullable=True),
    sa.Column('remote_scope', sa.String(length=32), nullable=True),
    sa.Column('eligible_states', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('excluded_states', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('timezone_requirement', sa.String(length=128), nullable=True),
    sa.Column('original_location', sa.String(length=255), nullable=True),
    sa.Column('salary_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('salary_period', sa.String(length=16), nullable=True),
    sa.Column('original_salary_text', sa.String(length=255), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_job_description', sa.Text(), nullable=True),
    sa.Column('cleaned_job_description', sa.Text(), nullable=True),
    sa.Column('responsibilities', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('required_skills', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('preferred_skills', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('extracted_keywords', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('requires_active_clearance', sa.Boolean(), nullable=False),
    sa.Column('canonical_fingerprint', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_fingerprint', name='uq_jobs_canonical_fingerprint'),
    sa.UniqueConstraint('source', 'source_job_id', name='uq_jobs_source_source_job_id')
    )
    op.create_index('ix_jobs_active_posted_at', 'jobs', ['active', 'posted_at'], unique=False)
    op.create_index('ix_jobs_company_name', 'jobs', ['company_name'], unique=False)
    op.create_index('ix_jobs_extracted_keywords', 'jobs', ['extracted_keywords'], unique=False, postgresql_using='gin')
    op.create_index('ix_jobs_full_technology_stack', 'jobs', ['full_technology_stack'], unique=False, postgresql_using='gin')
    op.create_index('ix_jobs_last_seen_at', 'jobs', ['last_seen_at'], unique=False)
    op.create_index('ix_jobs_level', 'jobs', ['level'], unique=False)
    op.create_index('ix_jobs_main_stack', 'jobs', ['main_stack'], unique=False, postgresql_using='gin')
    op.create_index('ix_jobs_role_category', 'jobs', ['role_category'], unique=False)
    op.create_index('ix_jobs_salary_range', 'jobs', ['salary_min', 'salary_max'], unique=False)
    op.create_index('ix_jobs_search_vector', 'jobs', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_table('sources',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('fetch_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('job_alt_sources',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_job_id', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_job_id', name='uq_job_alt_sources_source_source_job_id')
    )
    op.create_table('job_raw_payloads',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('job_id', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_job_id', sa.String(length=255), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.SmallInteger(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('jobs_fetched', sa.Integer(), nullable=False),
    sa.Column('jobs_new', sa.Integer(), nullable=False),
    sa.Column('jobs_updated', sa.Integer(), nullable=False),
    sa.Column('jobs_filtered_out', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_source_runs_source_started', 'source_runs', ['source_id', 'started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_source_runs_source_started', table_name='source_runs')
    op.drop_table('source_runs')
    op.drop_table('job_raw_payloads')
    op.drop_table('job_alt_sources')
    op.drop_table('sources')
    op.drop_index('ix_jobs_search_vector', table_name='jobs', postgresql_using='gin')
    op.drop_index('ix_jobs_salary_range', table_name='jobs')
    op.drop_index('ix_jobs_role_category', table_name='jobs')
    op.drop_index('ix_jobs_main_stack', table_name='jobs', postgresql_using='gin')
    op.drop_index('ix_jobs_level', table_name='jobs')
    op.drop_index('ix_jobs_last_seen_at', table_name='jobs')
    op.drop_index('ix_jobs_full_technology_stack', table_name='jobs', postgresql_using='gin')
    op.drop_index('ix_jobs_extracted_keywords', table_name='jobs', postgresql_using='gin')
    op.drop_index('ix_jobs_company_name', table_name='jobs')
    op.drop_index('ix_jobs_active_posted_at', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_ats_companies_enabled_platform', table_name='ats_companies')
    op.drop_table('ats_companies')
    # ### end Alembic commands ###
